version: "3.8"
services:
  Discofy:
    build: 
      context: .
      target: runner
    image: girlhack24:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      API_URL: ${API_URL}
      SECRET_KEY: ${SECRET_KEY}
      AUTH0_SECRET: ${AUTH0_SECRET}
      AUTH0_BASE_URL: ${AUTH0_BASE_URL}
      AUTH0_ISSUER_BASE_URL: ${AUTH0_ISSUER_BASE_URL}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}